/**
 * Description: <br>
 *
 * @author: bks <br>
 * @createDate: 2019-01-29 <br>
 */
package org.jing.web.db.object.item;

/*
Description: O_ITEM
 CREATE TABLE O_ITEM
 (
 ID            VARCHAR2(9) NOT NULL,
 NAME          VARCHAR2(40) NOT NULL,
 AUTHOR        VARCHAR2(40),
 ORG           VARCHAR2(40),
 SEQ           NUMBER,
 PARTY         VARCHAR2(40),
 ORIG_LANGUAGE VARCHAR2(20),
 LANGUAGE      VARCHAR2(20),
 SPEC          VARCHAR2(20),
 EVENT         VARCHAR2(10),
 STATE         VARCHAR2(1),
 CRT_DATE      DATE,
 CRT_USER      NUMBER,
 MOD_DATE      DATE,
 MOD_USER      NUMBER,
 EXT_ATTR3     VARCHAR2(100),
 EXT_ATTR4     VARCHAR2(100),
 EXT_ATTR5     VARCHAR2(100),
 EXT_ATTR6     VARCHAR2(100),
 EXT_ATTR7     VARCHAR2(100),
 EXT_ATTR8     VARCHAR2(100),
 EXT_ATTR9     VARCHAR2(100),
 EXT_ATTR10    VARCHAR2(100),
 EXT_ATTR11    VARCHAR2(100),
 EXT_ATTR12    VARCHAR2(100),
 EXT_ATTR13    VARCHAR2(100),
 EXT_ATTR14    VARCHAR2(100),
 EXT_ATTR15    VARCHAR2(100),
 EXT_ATTR16    VARCHAR2(100)
 )
 TABLESPACE USERS
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
 INITIAL 64K
 NEXT 1M
 MINEXTENTS 1
 MAXEXTENTS UNLIMITED
 );
 ALTER TABLE O_ITEM
 ADD CONSTRAINT PK_O_ITEM_ID PRIMARY KEY (ID)
 USING INDEX
 TABLESPACE USERS
 PCTFREE 10
 INITRANS 2
 MAXTRANS 255
 STORAGE
 (
 INITIAL 64K
 NEXT 1M
 MINEXTENTS 1
 MAXEXTENTS UNLIMITED
 );
 ALTER TABLE O_ITEM
 ADD CONSTRAINT FK_O_ITEM_CRT_USER FOREIGN KEY (CRT_USER)
 REFERENCES BM_USER (ID);
 */