/**
 * Description: <br>
 *
 * @author: bks <br>
 * @createDate: 2019-01-25 <br>
 */
package org.jing.web.db.bm.user;
/*
 Description: BM_USER.
 CREATE TABLE BM_USER
 (
 ID               NUMBER(6) NOT NULL,
 NAME             VARCHAR2(40),
 ACCOUNT          VARCHAR2(20),
 PASSWORD         VARCHAR2(20),
 ROLE             NUMBER(6) NOT NULL,
 SEX              VARCHAR2(3) NOT NULL,
 CRT_DATE         DATE NOT NULL,
 LAST_LOGIN_DATE  DATE,
 LAST_LOGOUT_DATE DATE,
 LAST_OPER_DATE   DATE,
 STATE            VARCHAR2(1) NOT NULL
 )
 TABLESPACE USERS
 PCTFREE 10
 INITRANS 1
 MAXTRANS 255
 STORAGE
 (
 INITIAL 64K
 NEXT 1M
 MINEXTENTS 1
 MAXEXTENTS UNLIMITED
 );
 ALTER TABLE BM_USER
 ADD PRIMARY KEY (ID)
 USING INDEX
 TABLESPACE USERS
 PCTFREE 10
 INITRANS 2
 MAXTRANS 255
 STORAGE
 (
 INITIAL 64K
 NEXT 1M
 MINEXTENTS 1
 MAXEXTENTS UNLIMITED
 );
 ALTER TABLE BM_USER
 ADD UNIQUE (NAME)
 USING INDEX
 TABLESPACE USERS
 PCTFREE 10
 INITRANS 2
 MAXTRANS 255
 STORAGE
 (
 INITIAL 64K
 NEXT 1M
 MINEXTENTS 1
 MAXEXTENTS UNLIMITED
 );
 ALTER TABLE BM_USER
 ADD UNIQUE (ACCOUNT)
 USING INDEX
 TABLESPACE USERS
 PCTFREE 10
 INITRANS 2
 MAXTRANS 255
 STORAGE
 (
 INITIAL 64K
 NEXT 1M
 MINEXTENTS 1
 MAXEXTENTS UNLIMITED
 );
 */